# This is a basic workflow to help you get started with Actions
name: elecfans club automatic check-in

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # runs at 00:00 UTC every day
  schedule:
    - cron:  '5 23 * * *'
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/actions_elecfans.yml'
      - 'actions_elecfans.py'
      - 'elecfans_club.py'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/actions_elecfans.yml'
      - 'actions_elecfans.py'
      - 'elecfans_club.py'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
    - name: Sign In
      timeout-minutes: 70
      env:
        CLUB_USERNAME: ${{ secrets.ELECFANS_ACCOUNT }}
        CLUB_PASSWORD: ${{ secrets.ELECFANS_PASSWORD }}
      run: |
        python actions_elecfans.py
        echo "CLUB_SCORES=$(cat sign_in_scores.txt)" >> $GITHUB_ENV
    - name: 'Get Date'
      run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
