# This is a basic workflow to help you get started with Actions
name: rt-thread club automatic check-in

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # runs at 00:00 UTC every day
  schedule:
    - cron:  '5 23,11 * * *'
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/actions_rtt.yml'
      - 'actions_rtt.py'
      - 'rt_thread_club.py'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/actions_rtt.yml'
      - 'actions_rtt.py'
      - 'rt_thread_club.py'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
    - name: 'Date'
      run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
    - name: Sign In
      timeout-minutes: 70
      env:
        CLUB_USERNAME: ${{ secrets.USERNAME }}
        CLUB_PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python actions_rtt.py
        echo "CLUB_DAY_NUMERS=$(cat sign_in_days.txt)" >> $GITHUB_ENV
